I'm sorry, but an uncaught exception occurred.

While running game code:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\curti\\code\\renpy-fuckabout\\RenpyFuckabout\\game\\saves\\persistent.1689129200.tmp'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "Q:\RenPy\renpy-8.1.1-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "Q:\RenPy\renpy-8.1.1-sdk\renpy\main.py", line 684, in main
    renpy.persistent.update(True)
  File "Q:\RenPy\renpy-8.1.1-sdk\renpy\persistent.py", line 401, in update
    save()
  File "Q:\RenPy\renpy-8.1.1-sdk\renpy\persistent.py", line 419, in save
    renpy.loadsave.location.save_persistent(compressed)
  File "Q:\RenPy\renpy-8.1.1-sdk\renpy\savelocation.py", line 545, in save_persistent
    l.save_persistent(data)
  File "Q:\RenPy\renpy-8.1.1-sdk\renpy\savelocation.py", line 374, in save_persistent
    with open(fn_tmp, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\curti\\code\\renpy-fuckabout\\RenpyFuckabout\\game\\saves\\persistent.1689129200.tmp'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.1.23060707
Capilano 1.0
Tue Jul 11 21:15:37 2023
